# Welcome to yourown-bootstrap4!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically.

# Site settings
title: zee
email: your-email@domain.com
description: > # this means to ignore newlines until "twitter_username:"
  Documentation of zee
twitter_username: bdavidxyz
github_username:  bdavidxyz

# Build settings
markdown: kramdown

# Exclude nodes artifacts from build
exclude:
  - package.json
  - node_modules
  - gulpfile.js
  - README.md
